// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDgcsSkfKV-EO9kv2hDZxRyPHdfq4bwis',
    appId: '1:1015493923928:web:eef17cb70e7933b335662d',
    messagingSenderId: '1015493923928',
    projectId: 'taskmaster-b2477',
    authDomain: 'taskmaster-b2477.firebaseapp.com',
    storageBucket: 'taskmaster-b2477.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXonFXA0VTw4jJgKYqs9v1ahg7GC6Jme4',
    appId: '1:1015493923928:android:c688da89eec0da0235662d',
    messagingSenderId: '1015493923928',
    projectId: 'taskmaster-b2477',
    storageBucket: 'taskmaster-b2477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdQzbF3yYt1nJOmBOEaGuRu3f0UApOAs',
    appId: '1:1015493923928:ios:c68ec00c01f11f8b35662d',
    messagingSenderId: '1015493923928',
    projectId: 'taskmaster-b2477',
    storageBucket: 'taskmaster-b2477.appspot.com',
    iosBundleId: 'com.example.taskmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvdQzbF3yYt1nJOmBOEaGuRu3f0UApOAs',
    appId: '1:1015493923928:ios:c68ec00c01f11f8b35662d',
    messagingSenderId: '1015493923928',
    projectId: 'taskmaster-b2477',
    storageBucket: 'taskmaster-b2477.appspot.com',
    iosBundleId: 'com.example.taskmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDgcsSkfKV-EO9kv2hDZxRyPHdfq4bwis',
    appId: '1:1015493923928:web:226acfcaaec9014f35662d',
    messagingSenderId: '1015493923928',
    projectId: 'taskmaster-b2477',
    authDomain: 'taskmaster-b2477.firebaseapp.com',
    storageBucket: 'taskmaster-b2477.appspot.com',
  );
}
